### ISSUE TITLE
YC login 

### ISSUE THREAD

**Issue by MeRuslan** [yc-actions/ideas#1]
Самый простой, и самый flexible. Нужна функция просто залогиниться, и использовать yandex cloud CLI в самих action, все нужные штуки отдельными для них actions не покрыть все-таки.

**Comment by nikolaymatrosov** [comment]
Вот action, чтобы выписать YC IAM токен. https://github.com/yc-actions/yc-iam-token
Дальше конечно еще нужно собрать экшен, который будет привозить докер контейнер с YC CLI и запускать в нем произвольные команды. До этого у меня руки не дошли.
