### ISSUE TITLE
Deploy static sites to YC public buckets

### ISSUE THREAD

**Issue by v-kolesnikov** [yc-actions/ideas#2]
Возможно уже есть где и я пока просто не вижу action для автоматизации доставки статического сайта в YC public bucket.

https://cloud.yandex.ru/docs/tutorials/web/static#create-public-bucket

**Comment by nikolaymatrosov** [comment]
По идее вы можете использовать любой экшен, который привозит AWS CLI и передать ему нужные параметры авторизации. Access и Secret ключи и endpoint YC.
