### ISSUE TITLE
docs and examples

### ISSUE THREAD

**Issue by vladisalv** [yc-actions/ideas#3]
Хочется репозиторий со сложными примерами, где на каком-нибудь реальном helloworld будут задействоваться все текущие actions. Сейчас каждый экшн надо руками пробовать, чтобы понять что он делает. Например, yc-lockbox: вроде использовать просто, но как и куда потом этот ключ прокидывать... сходу не понятно.

Ну и добавить ссылку на эту репу во все ридмишки.

**Comment by nikolaymatrosov** [comment]
https://nikolaymatrosov.medium.com/github-actions-для-построения-cd-в-yandex-cloud-dad32815af18
https://www.youtube.com/watch?v=NKhKuQhSktU и пример оттуда https://github.com/yandex-cloud/examples/tree/master/serverless/cicd-django
