### ISSUE TITLE
Деплоить образ  в instance group с COI

### ISSUE THREAD

**Issue by nar3k** [yc-actions/ideas#4]
Есть простой сервис на базе COI но хочется сделать его отказоустойчивым, можно ли сделать action который будет собирать образ и  далее обновлять compose спеку инстанс группы с COI?

**Comment by nikolaymatrosov** [comment]
Готово. https://github.com/yc-actions/yc-coi-deploy-ig/tree/main

**Comment by nar3k** [comment]
Спасибо! Я протестирую и вернусь уже если будут проблемы по факту!
