### ISSUE TITLE
Actions для загрузки сайта на S3

### ISSUE THREAD

**Issue by MrMeison** [yc-actions/ideas#5]
Написал небольшой actions для загрузки сайта на YC Object Storage.
Из главных бонусов:
- настриваемый
- быстрый
- проставляет правильные mime-типы

https://github.com/MrMeison/yc-object-storage-action

**Comment by nikolaymatrosov** [comment]
Спасибо, но аналогичный экшен уже существует. https://github.com/yc-actions/yc-obj-storage-upload

**Comment by MrMeison** [comment]
Да, я видел, но с ходу не получилось завести через AIM, в этом плане статический ключ виглядит удобнее.
Плюсом, кажется, мой вариант несколько быстрее за счет параллельности отправки запросов.
Было бы классно если бы ты хотя бы рассмотрел возможность расширить(?) API экшена и слегка потюнить по скорости работы.
